/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.londonmusical.lmts.screens;

import javax.swing.JInternalFrame;

/**
 *
 * @author ektasingh
 */
public class AdminControlPanel extends javax.swing.JFrame {

    /**
     * Creates new form AdminControlPanel
     */
    String adminuser;
    public AdminControlPanel() {
        initComponents();
    }
    
    public AdminControlPanel(String auser) {
        this.adminuser=auser;
        initComponents();
        String getValue=welcome.getText();
        welcome.setText(getValue+ " "+auser);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        welcome = new javax.swing.JLabel();
        showPane = new javax.swing.JDesktopPane();
        logoutButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        manageShows = new javax.swing.JMenu();
        addShowDetails = new javax.swing.JMenuItem();
        allShowDetails = new javax.swing.JMenuItem();
        booking = new javax.swing.JMenu();
        bookingDetails = new javax.swing.JMenuItem();
        manageAdmin = new javax.swing.JMenu();
        addAdmin = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        jMenuItem3.setText("jMenuItem3");

        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        welcome.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        welcome.setText("Welcome!");

        showPane.setBackground(new java.awt.Color(238, 238, 238));

        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        manageShows.setText("Manage Shows");

        addShowDetails.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.ALT_DOWN_MASK));
        addShowDetails.setText("Add Show Details");
        addShowDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addShowDetailsActionPerformed(evt);
            }
        });
        manageShows.add(addShowDetails);

        allShowDetails.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.ALT_DOWN_MASK));
        allShowDetails.setText("All Show Details");
        allShowDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allShowDetailsActionPerformed(evt);
            }
        });
        manageShows.add(allShowDetails);

        jMenuBar1.add(manageShows);

        booking.setText("Booking");

        bookingDetails.setText("Booking Details");
        bookingDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingDetailsActionPerformed(evt);
            }
        });
        booking.add(bookingDetails);

        jMenuBar1.add(booking);

        manageAdmin.setText("Manage Users");

        addAdmin.setText("Add Admin");
        addAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAdminActionPerformed(evt);
            }
        });
        manageAdmin.add(addAdmin);

        jMenuBar1.add(manageAdmin);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(logoutButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(welcome)
                        .addGap(146, 146, 146))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(showPane)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(welcome)
                    .addComponent(logoutButton))
                .addGap(18, 18, 18)
                .addComponent(showPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addShowDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addShowDetailsActionPerformed
        // TODO add your handling code here:
        JInternalFrame[] frames = showPane.getAllFrames();

        for (JInternalFrame frame : frames) {
                frame.dispose();
        }
        AddShowDetails asd=new AddShowDetails();
        showPane.add(asd);
        asd.show();
    }//GEN-LAST:event_addShowDetailsActionPerformed

    private void bookingDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingDetailsActionPerformed
        // TODO add your handling code here:
        JInternalFrame[] frames = showPane.getAllFrames();

        for (JInternalFrame frame : frames) {
                frame.dispose();
        }
        AllBookingDetails abd=new AllBookingDetails();
        showPane.add(abd);
        abd.show();
    }//GEN-LAST:event_bookingDetailsActionPerformed

    private void allShowDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allShowDetailsActionPerformed
        // TODO add your handling code here:
        JInternalFrame[] frames = showPane.getAllFrames();

        for (JInternalFrame frame : frames) {
                frame.dispose();
        }
        AllShowDetials asd=new AllShowDetials();
        showPane.add(asd);
        asd.show();
    }//GEN-LAST:event_allShowDetailsActionPerformed

    private void addAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAdminActionPerformed
        // TODO add your handling code here:
        JInternalFrame[] frames = showPane.getAllFrames();

        for (JInternalFrame frame : frames) {
                frame.dispose();
        }
        AllUserDetails aud=new AllUserDetails();
        showPane.add(aud);
        aud.show();
    }//GEN-LAST:event_addAdminActionPerformed

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        // TODO add your handling code here:
        dispose();
        UserLogin ul = new UserLogin();
        ul.setLocationRelativeTo(null);
        ul.setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminControlPanel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminControlPanel().setVisible(true);
            }
        });
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem addAdmin;
    private javax.swing.JMenuItem addShowDetails;
    private javax.swing.JMenuItem allShowDetails;
    private javax.swing.JMenu booking;
    private javax.swing.JMenuItem bookingDetails;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JButton logoutButton;
    private javax.swing.JMenu manageAdmin;
    private javax.swing.JMenu manageShows;
    private javax.swing.JDesktopPane showPane;
    private javax.swing.JLabel welcome;
    // End of variables declaration//GEN-END:variables
}
