/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.londonmusical.lmts.screens;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Objects;
import java.util.Vector;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author ektasingh
 */
public class BookMusical extends javax.swing.JInternalFrame {

    String username;
    int studentPrice;
    int adultPrice;
    int seniorPrice;

    /**
     * Creates new form BookMusical
     */
    public BookMusical(String user) {
        username = user;
        initComponents();
        populateComboBox();
        showsField.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                // Update the JTextArea when an item is selected in the JComboBox
                populateTextArea();
            }
        });
    }

    private void populateComboBox() {

        try {
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/lmts", "root", "root");
            Statement stat = con.createStatement();
            String selectQuery = "SELECT name FROM ROOT.\"Shows\"";
            Vector<String> showNames = new Vector<>();
            try (PreparedStatement preparedStatement = con.prepareStatement(selectQuery)) {
                ResultSet resultSet = preparedStatement.executeQuery();

                // Add venue names to the Vector
                while (resultSet.next()) {
                    showNames.add(resultSet.getString("name"));
                }
                showsField.setModel(new DefaultComboBoxModel<>(showNames));
                // Populate the JComboBox with the venue names
                resultSet.close();
                stat.close();
                con.close();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading data from the database!");
        }

    }

    private void populateTextArea() {
        String showName = Objects.requireNonNull(showsField.getSelectedItem()).toString();
        try {
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/lmts", "root", "root");
            Statement stat = con.createStatement();
            String selectQuery = "SELECT * FROM ROOT.\"Shows\" WHERE name='" + showName + "'";
            try (PreparedStatement preparedStatement = con.prepareStatement(selectQuery)) {
                ResultSet resultSet = preparedStatement.executeQuery();
                // Add venue names to the Vector

                while (resultSet.next()) {
                    String name = resultSet.getString("NAME");
                    String runtime = resultSet.getString("RUNTIME");
                    String categories = resultSet.getString("CATEGORIES");
                    String venue = resultSet.getString("VENUE");
                    studentPrice = Integer.parseInt(resultSet.getString("STUDENT_PRICE"));
                    adultPrice = Integer.parseInt(resultSet.getString("ADULT_PRICE"));
                    seniorPrice = Integer.parseInt(resultSet.getString("SENIOR_PRICE"));
                    String showDetails = "Name: " + name + "\n"
                            + "RunTIME: " + runtime + "\n"
                            + "Categories: " + categories + "\n"
                            + "Venue: " + venue + "\n"
                            + "Student Price: $" + studentPrice + "\n"
                            + "Adult Price: $" + adultPrice + "\n"
                            + "Senior Price: $" + seniorPrice + "";
                    showsTextArea.setText(showDetails);
                }
                resultSet.close();
                stat.close();
                con.close();
            }
        } catch (SQLException ex) {
            ex.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error loading data from the database!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BookMusical = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        showsLabel = new javax.swing.JLabel();
        showsField = new javax.swing.JComboBox<>();
        timeLabel = new javax.swing.JLabel();
        timeField = new javax.swing.JComboBox<>();
        venueLabel = new javax.swing.JLabel();
        venueField = new javax.swing.JComboBox<>();
        studentTicketsField = new javax.swing.JComboBox<>();
        studentTicketLabel = new javax.swing.JLabel();
        seniorTicketLabel = new javax.swing.JLabel();
        nameField1 = new javax.swing.JTextField();
        paymentLabel = new javax.swing.JLabel();
        paymentField = new javax.swing.JComboBox<>();
        BookButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        showsTextArea = new javax.swing.JTextArea();
        seniorTicketField = new javax.swing.JComboBox<>();
        adultTicketLabel = new javax.swing.JLabel();
        adultTicketField = new javax.swing.JComboBox<>();

        BookMusical.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        BookMusical.setText("Book Musical");

        nameLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        nameLabel.setText("Name");

        showsLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        showsLabel.setText("Shows");

        showsField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        timeLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        timeLabel.setText("Time");

        timeField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "6 PM", "8PM", "10 PM" }));

        venueLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        venueLabel.setText("Venue");

        venueField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ambassedor Theatre", "Derby Theatre", "Roscomm Theatre", "Lucan Theatre" }));

        studentTicketsField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));

        studentTicketLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        studentTicketLabel.setText("Student");

        seniorTicketLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        seniorTicketLabel.setText("Senior");

        nameField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameField1ActionPerformed(evt);
            }
        });

        paymentLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        paymentLabel.setText("Payment");

        paymentField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "CASH", "ONLINE", "BANK TRANSFER" }));

        BookButton.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        BookButton.setText("Book");
        BookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookButtonActionPerformed(evt);
            }
        });

        showsTextArea.setColumns(20);
        showsTextArea.setRows(5);
        jScrollPane1.setViewportView(showsTextArea);

        seniorTicketField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        seniorTicketField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seniorTicketFieldActionPerformed(evt);
            }
        });

        adultTicketLabel.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        adultTicketLabel.setText("Adult");

        adultTicketField.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8" }));
        adultTicketField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adultTicketFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(BookMusical)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(showsLabel)
                            .addComponent(nameLabel)
                            .addComponent(paymentLabel)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(timeLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(studentTicketLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(venueLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(studentTicketsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seniorTicketLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(seniorTicketField, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(showsField, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(venueField, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paymentField, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(timeField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adultTicketLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(adultTicketField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 9, Short.MAX_VALUE)))
                .addGap(61, 61, 61)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(BookButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(33, 33, 33))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(BookMusical)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nameLabel)
                            .addComponent(nameField1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(showsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(showsLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(venueField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(venueLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(studentTicketLabel)
                            .addComponent(studentTicketsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seniorTicketLabel)
                            .addComponent(seniorTicketField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(timeLabel)
                            .addComponent(timeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adultTicketLabel)
                            .addComponent(adultTicketField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(paymentLabel)
                            .addComponent(paymentField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BookButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nameField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameField1ActionPerformed

    private void BookButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookButtonActionPerformed
        // TODO add your handling code here:
        String name = this.nameField1.getText();
        String showName = (String) this.showsField.getSelectedItem();
        String time = (String) this.timeField.getSelectedItem();
        String venue = (String) this.venueField.getSelectedItem();

        String studentTicketsString = (String) this.studentTicketsField.getSelectedItem();
        int studentTickets = Integer.parseInt(studentTicketsString);
        String adultTicketsString = (String) this.adultTicketField.getSelectedItem();
        int adultTickets = Integer.parseInt(adultTicketsString);
        String seniorTicketsString = (String) this.seniorTicketField.getSelectedItem();
        int seniorTickets = Integer.parseInt(seniorTicketsString);

        String payment = (String) this.paymentField.getSelectedItem();
        int amount = (studentTickets*studentPrice) + (adultTickets*adultPrice) + (seniorTickets*seniorPrice);

        try {

            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/lmts", "root", "root");
            Statement stat = con.createStatement();

            try {
                String insertQuery = "insert into ROOT.\"Booking\"(USERNAME, BOOKING_NAME, SHOW_NAME, SHOW_TIME, SHOW_VENUE, STUDENT_TICKETS, ADULT_TICKETS, SENIOR_TICKETS, AMOUNT, PAYMENT) values('" + username + "','" + name + "','" + showName + "','" + time + "','" + venue + "'," + studentTickets + "," + adultTickets + "," + seniorTickets + "," + amount + ",'" + payment + "')";
                stat.executeUpdate(insertQuery);
                infoMessage("Tickets Booked, Download your tickets from My Bookings", "Booking Information");
            } catch (Exception e) {
                System.out.println(e);
            }
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_BookButtonActionPerformed

    private void seniorTicketFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seniorTicketFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seniorTicketFieldActionPerformed

    private void adultTicketFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adultTicketFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adultTicketFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookButton;
    private javax.swing.JLabel BookMusical;
    private javax.swing.JComboBox<String> adultTicketField;
    private javax.swing.JLabel adultTicketLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nameField1;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JComboBox<String> paymentField;
    private javax.swing.JLabel paymentLabel;
    private javax.swing.JComboBox<String> seniorTicketField;
    private javax.swing.JLabel seniorTicketLabel;
    private javax.swing.JComboBox<String> showsField;
    private javax.swing.JLabel showsLabel;
    private javax.swing.JTextArea showsTextArea;
    private javax.swing.JLabel studentTicketLabel;
    private javax.swing.JComboBox<String> studentTicketsField;
    private javax.swing.JComboBox<String> timeField;
    private javax.swing.JLabel timeLabel;
    private javax.swing.JComboBox<String> venueField;
    private javax.swing.JLabel venueLabel;
    // End of variables declaration//GEN-END:variables

    public void infoMessage(String message, String tittle) {
        JOptionPane.showMessageDialog(null, message, tittle, JOptionPane.INFORMATION_MESSAGE);
    }
}
